name: Release to PyPI

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write  # Grant permissions to generate an OIDC token

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        # Install required packages, including twine for publishing
        python -m pip install --upgrade pip setuptools wheel build twine

    - name: Build package
      run: |
        # Use 'build' to create source and wheel distributions
        python -m build

    - name: Publish to PyPI using OIDC
      run: |
        # Use 'twine' to upload the built distributions to PyPI
        python -m twine upload --repository pypi dist/*
