name: Release to PyPI

on:
  workflow_dispatch:

permissions:
  contents: read         # Required to read repository contents
  id-token: write        # Required to generate OIDC token for authentication

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel build

    - name: Build package
      run: |
        python -m build sdist

    - name: Publish to PyPI using OIDC
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://upload.pypi.org/legacy/
        environment: "Any"  # Match with the environment specified in PyPI
        verbose: true