name: Release to PyPI

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: read      # Allows read access to the repository contents
  id-token: write     # Required for generating OIDC token for authentication with PyPI

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Step 3: Install required dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel build

    # Step 4: Build the package
    - name: Build package
      run: |
        python -m build

    # Step 5: Publish to PyPI using OIDC
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://upload.pypi.org/legacy/
        environment: "Any"  # Set this to match your environment name in PyPI's pending publisher
